export const defaultSpecialTourCategories = [
  {
    slug: "naming-ceremony",
    label: "Naming ceremony",
    line: "Outdooring, kente, and the names a family speaks into a child.",
    sortOrder: 0,
    tourPrice: 0,
    tourDuration: "1 Day",
    images: [],
  },
  {
    slug: "food",
    label: "Food",
    line: "Jollof, banku, waakye, and the night markets that feed Accra.",
    sortOrder: 1,
    tourPrice: 0,
    tourDuration: "1 Day",
    images: [],
  },
  {
    slug: "nightlife",
    label: "Nightlife",
    line: "Highlife, hiplife, and rooms that do not empty until the sun is up.",
    sortOrder: 2,
    tourPrice: 0,
    tourDuration: "1 Day",
    images: [],
  },
  {
    slug: "tour",
    label: "Tour",
    line: "Nature, beach, and bus - canopy, coast, and the road between them.",
    sortOrder: 3,
    tourPrice: 0,
    tourDuration: "1 Day",
    images: [],
  },
  {
    slug: "experience",
    label: "Experience",
    line: "Kente, weaving, tie-dye, clay, and the kitchen - skills you take home in your hands.",
    sortOrder: 4,
    tourPrice: 0,
    tourDuration: "1 Day",
    images: [],
  },
  {
    slug: "heritage",
    label: "Heritage",
    line: "Walk the door of no return with a guide who will not rush you.",
    sortOrder: 5,
    tourPrice: 0,
    tourDuration: "1 Day",
    images: [],
  },
  {
    slug: "games",
    label: "Games",
    line: "Oware in the courtyard, and football that stops a whole street.",
    sortOrder: 6,
    tourPrice: 0,
    tourDuration: "1 Day",
    images: [],
  },
  {
    slug: "festivals",
    label: "Festivals",
    line: "Homowo, Aboakyer, chieftaincy, and the calendar that still runs the year.",
    sortOrder: 7,
    tourPrice: 0,
    tourDuration: "1 Day",
    images: [],
  },
];

export const productCategories = [
  "Fashion",
  "Accessories",
  "Beauty",
  "Art",
  "Books",
  "Home",
  "Souvenirs",
  "Food",
  "Travel",
];

export const ADMIN_COOKIE = "kc_admin";
